/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created: Sun Jul 8 13:00:56 2018
**      by: Qt User Interface Compiler version 4.6.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QSlider>
#include <QtGui/QStatusBar>
#include <QtGui/QTableView>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTableView *table;
    QFrame *frame;
    QSlider *setAngleSilder0;
    QLabel *label;
    QLineEdit *Line0;
    QPushButton *ButtonAngle0Down;
    QPushButton *ButtonAngle0Up;
    QFrame *frame_2;
    QSlider *setAngleSilder1;
    QLabel *label_2;
    QLineEdit *Line1;
    QPushButton *ButtonAngle1Down;
    QPushButton *ButtonAngle1Up;
    QFrame *frame_3;
    QSlider *setAngleSilder2;
    QLabel *label_3;
    QLineEdit *Line2;
    QPushButton *ButtonAngle2Up;
    QPushButton *ButtonAngle2Down;
    QFrame *frame_4;
    QSlider *setAngleSilder3;
    QLabel *label_4;
    QLineEdit *Line3;
    QPushButton *ButtonAngle3Up;
    QPushButton *ButtonAngle3Down;
    QFrame *frame_5;
    QSlider *setAngleSilder4;
    QLabel *label_5;
    QLineEdit *Line4;
    QPushButton *ButtonAngle4Down;
    QPushButton *ButtonAngle4Up;
    QFrame *frame_6;
    QSlider *setAngleSilder5;
    QLabel *label_7;
    QLineEdit *Line5;
    QPushButton *ButtonAngle5Up;
    QPushButton *ButtonAngle5Down;
    QFrame *frame_7;
    QSlider *setAngleSilder6;
    QLabel *label_8;
    QLineEdit *Line6;
    QPushButton *ButtonAngle6Up;
    QPushButton *ButtonAngle6Down;
    QFrame *frame_8;
    QSlider *setAngleSilder8;
    QLabel *label_9;
    QLineEdit *Line8;
    QPushButton *ButtonAngle8Down;
    QPushButton *ButtonAngle8Up;
    QFrame *frame_9;
    QSlider *setAngleSilder9;
    QLabel *label_10;
    QLineEdit *Line9;
    QPushButton *ButtonAngle9Down;
    QPushButton *ButtonAngle9Up;
    QFrame *frame_10;
    QSlider *setAngleSilder7;
    QLabel *label_11;
    QLineEdit *Line7;
    QPushButton *ButtonAngle7Down;
    QPushButton *ButtonAngle7Up;
    QLineEdit *line_time;
    QPushButton *send;
    QLabel *label_6;
    QFrame *frame_11;
    QPushButton *ButtonRunAll;
    QPushButton *feedback;
    QPushButton *ButtonChooseFile;
    QPushButton *insert;
    QPushButton *SaveFile;
    QPushButton *CleanTable;
    QPushButton *dele;
    QPushButton *ButtonCountZero;
    QFrame *frame_12;
    QSlider *setAngleSilder10;
    QLabel *label_13;
    QLineEdit *Line10;
    QPushButton *ButtonAngle10Down;
    QPushButton *ButtonAngle10Up;
    QFrame *frame_13;
    QSlider *setAngleSilder11;
    QLabel *label_14;
    QLineEdit *Line11;
    QPushButton *ButtonAngle11Down;
    QPushButton *ButtonAngle11Up;
    QFrame *frame_14;
    QSlider *setAngleSilder12;
    QLabel *label_15;
    QLineEdit *Line12;
    QPushButton *ButtonAngle12Down;
    QPushButton *ButtonAngle12Up;
    QFrame *frame_15;
    QSlider *setAngleSilder13;
    QLabel *label_16;
    QLineEdit *Line13;
    QPushButton *ButtonAngle13Down;
    QPushButton *ButtonAngle13Up;
    QFrame *frame_16;
    QSlider *setAngleSilder14;
    QLabel *label_17;
    QLineEdit *Line14;
    QPushButton *ButtonAngle14Down;
    QPushButton *ButtonAngle14Up;
    QFrame *frame_17;
    QSlider *setAngleSilder15;
    QLabel *label_19;
    QLineEdit *Line15;
    QPushButton *ButtonAngle15Down;
    QPushButton *ButtonAngle15Up;
    QFrame *frame_18;
    QSlider *setAngleSilder16;
    QLabel *label_20;
    QLineEdit *Line16;
    QPushButton *ButtonAngle16Down;
    QPushButton *ButtonAngle16Up;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1790, 945);
        MainWindow->setStyleSheet(QString::fromUtf8("QGroupBox {  rgb(255, 0, 0)}"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        table = new QTableView(centralWidget);
        table->setObjectName(QString::fromUtf8("table"));
        table->setGeometry(QRect(1100, 30, 681, 411));
        frame = new QFrame(centralWidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(270, 380, 221, 81));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Sunken);
        frame->setLineWidth(4);
        setAngleSilder0 = new QSlider(frame);
        setAngleSilder0->setObjectName(QString::fromUtf8("setAngleSilder0"));
        setAngleSilder0->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder0->setMinimum(-90);
        setAngleSilder0->setMaximum(90);
        setAngleSilder0->setPageStep(1);
        setAngleSilder0->setOrientation(Qt::Horizontal);
        label = new QLabel(frame);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(31, 10, 91, 31));
        QFont font;
        font.setFamily(QString::fromUtf8("Adobe Arabic"));
        font.setPointSize(28);
        label->setFont(font);
        Line0 = new QLineEdit(frame);
        Line0->setObjectName(QString::fromUtf8("Line0"));
        Line0->setGeometry(QRect(121, 10, 51, 31));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Adobe Arabic"));
        font1.setPointSize(24);
        Line0->setFont(font1);
        ButtonAngle0Down = new QPushButton(frame);
        ButtonAngle0Down->setObjectName(QString::fromUtf8("ButtonAngle0Down"));
        ButtonAngle0Down->setGeometry(QRect(180, 40, 31, 21));
        ButtonAngle0Up = new QPushButton(frame);
        ButtonAngle0Up->setObjectName(QString::fromUtf8("ButtonAngle0Up"));
        ButtonAngle0Up->setGeometry(QRect(180, 10, 31, 21));
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(270, 480, 221, 81));
        frame_2->setFrameShape(QFrame::Box);
        frame_2->setFrameShadow(QFrame::Sunken);
        frame_2->setLineWidth(4);
        setAngleSilder1 = new QSlider(frame_2);
        setAngleSilder1->setObjectName(QString::fromUtf8("setAngleSilder1"));
        setAngleSilder1->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder1->setMinimum(-100);
        setAngleSilder1->setMaximum(100);
        setAngleSilder1->setPageStep(1);
        setAngleSilder1->setOrientation(Qt::Horizontal);
        label_2 = new QLabel(frame_2);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(31, 10, 91, 31));
        label_2->setFont(font);
        Line1 = new QLineEdit(frame_2);
        Line1->setObjectName(QString::fromUtf8("Line1"));
        Line1->setGeometry(QRect(121, 10, 51, 31));
        Line1->setFont(font1);
        ButtonAngle1Down = new QPushButton(frame_2);
        ButtonAngle1Down->setObjectName(QString::fromUtf8("ButtonAngle1Down"));
        ButtonAngle1Down->setGeometry(QRect(180, 40, 31, 21));
        ButtonAngle1Up = new QPushButton(frame_2);
        ButtonAngle1Up->setObjectName(QString::fromUtf8("ButtonAngle1Up"));
        ButtonAngle1Up->setGeometry(QRect(180, 10, 31, 21));
        frame_3 = new QFrame(centralWidget);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(270, 580, 221, 81));
        frame_3->setFrameShape(QFrame::Box);
        frame_3->setFrameShadow(QFrame::Sunken);
        frame_3->setLineWidth(4);
        setAngleSilder2 = new QSlider(frame_3);
        setAngleSilder2->setObjectName(QString::fromUtf8("setAngleSilder2"));
        setAngleSilder2->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder2->setMinimum(-100);
        setAngleSilder2->setMaximum(100);
        setAngleSilder2->setPageStep(1);
        setAngleSilder2->setOrientation(Qt::Horizontal);
        label_3 = new QLabel(frame_3);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(31, 10, 91, 31));
        label_3->setFont(font);
        Line2 = new QLineEdit(frame_3);
        Line2->setObjectName(QString::fromUtf8("Line2"));
        Line2->setGeometry(QRect(121, 10, 51, 31));
        Line2->setFont(font1);
        ButtonAngle2Up = new QPushButton(frame_3);
        ButtonAngle2Up->setObjectName(QString::fromUtf8("ButtonAngle2Up"));
        ButtonAngle2Up->setGeometry(QRect(180, 10, 31, 21));
        ButtonAngle2Down = new QPushButton(frame_3);
        ButtonAngle2Down->setObjectName(QString::fromUtf8("ButtonAngle2Down"));
        ButtonAngle2Down->setGeometry(QRect(180, 40, 31, 21));
        frame_4 = new QFrame(centralWidget);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(260, 680, 241, 101));
        frame_4->setFrameShape(QFrame::Box);
        frame_4->setFrameShadow(QFrame::Sunken);
        frame_4->setLineWidth(4);
        setAngleSilder3 = new QSlider(frame_4);
        setAngleSilder3->setObjectName(QString::fromUtf8("setAngleSilder3"));
        setAngleSilder3->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder3->setMinimum(-90);
        setAngleSilder3->setMaximum(90);
        setAngleSilder3->setPageStep(1);
        setAngleSilder3->setOrientation(Qt::Horizontal);
        label_4 = new QLabel(frame_4);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(31, 10, 91, 31));
        label_4->setFont(font);
        Line3 = new QLineEdit(frame_4);
        Line3->setObjectName(QString::fromUtf8("Line3"));
        Line3->setGeometry(QRect(121, 10, 51, 31));
        Line3->setFont(font1);
        ButtonAngle3Up = new QPushButton(frame_4);
        ButtonAngle3Up->setObjectName(QString::fromUtf8("ButtonAngle3Up"));
        ButtonAngle3Up->setGeometry(QRect(190, 10, 31, 21));
        ButtonAngle3Down = new QPushButton(frame_4);
        ButtonAngle3Down->setObjectName(QString::fromUtf8("ButtonAngle3Down"));
        ButtonAngle3Down->setGeometry(QRect(190, 40, 31, 21));
        frame_5 = new QFrame(centralWidget);
        frame_5->setObjectName(QString::fromUtf8("frame_5"));
        frame_5->setGeometry(QRect(220, 790, 301, 101));
        frame_5->setFrameShape(QFrame::Box);
        frame_5->setFrameShadow(QFrame::Sunken);
        frame_5->setLineWidth(4);
        setAngleSilder4 = new QSlider(frame_5);
        setAngleSilder4->setObjectName(QString::fromUtf8("setAngleSilder4"));
        setAngleSilder4->setGeometry(QRect(60, 60, 141, 20));
        setAngleSilder4->setMinimum(-90);
        setAngleSilder4->setMaximum(90);
        setAngleSilder4->setPageStep(1);
        setAngleSilder4->setOrientation(Qt::Horizontal);
        label_5 = new QLabel(frame_5);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(61, 30, 91, 31));
        label_5->setFont(font);
        Line4 = new QLineEdit(frame_5);
        Line4->setObjectName(QString::fromUtf8("Line4"));
        Line4->setGeometry(QRect(151, 30, 51, 31));
        Line4->setFont(font1);
        ButtonAngle4Down = new QPushButton(frame_5);
        ButtonAngle4Down->setObjectName(QString::fromUtf8("ButtonAngle4Down"));
        ButtonAngle4Down->setGeometry(QRect(230, 50, 31, 21));
        ButtonAngle4Up = new QPushButton(frame_5);
        ButtonAngle4Up->setObjectName(QString::fromUtf8("ButtonAngle4Up"));
        ButtonAngle4Up->setGeometry(QRect(230, 20, 31, 21));
        frame_6 = new QFrame(centralWidget);
        frame_6->setObjectName(QString::fromUtf8("frame_6"));
        frame_6->setGeometry(QRect(620, 380, 221, 81));
        frame_6->setFrameShape(QFrame::Box);
        frame_6->setFrameShadow(QFrame::Sunken);
        frame_6->setLineWidth(4);
        setAngleSilder5 = new QSlider(frame_6);
        setAngleSilder5->setObjectName(QString::fromUtf8("setAngleSilder5"));
        setAngleSilder5->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder5->setMinimum(-90);
        setAngleSilder5->setMaximum(90);
        setAngleSilder5->setPageStep(1);
        setAngleSilder5->setOrientation(Qt::Horizontal);
        label_7 = new QLabel(frame_6);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(31, 10, 91, 31));
        label_7->setFont(font);
        Line5 = new QLineEdit(frame_6);
        Line5->setObjectName(QString::fromUtf8("Line5"));
        Line5->setGeometry(QRect(121, 10, 51, 31));
        Line5->setFont(font1);
        ButtonAngle5Up = new QPushButton(frame_6);
        ButtonAngle5Up->setObjectName(QString::fromUtf8("ButtonAngle5Up"));
        ButtonAngle5Up->setGeometry(QRect(180, 10, 31, 21));
        ButtonAngle5Down = new QPushButton(frame_6);
        ButtonAngle5Down->setObjectName(QString::fromUtf8("ButtonAngle5Down"));
        ButtonAngle5Down->setGeometry(QRect(180, 40, 31, 21));
        frame_7 = new QFrame(centralWidget);
        frame_7->setObjectName(QString::fromUtf8("frame_7"));
        frame_7->setGeometry(QRect(620, 480, 221, 81));
        frame_7->setFrameShape(QFrame::Box);
        frame_7->setFrameShadow(QFrame::Sunken);
        frame_7->setLineWidth(4);
        setAngleSilder6 = new QSlider(frame_7);
        setAngleSilder6->setObjectName(QString::fromUtf8("setAngleSilder6"));
        setAngleSilder6->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder6->setMinimum(-100);
        setAngleSilder6->setMaximum(100);
        setAngleSilder6->setPageStep(1);
        setAngleSilder6->setOrientation(Qt::Horizontal);
        label_8 = new QLabel(frame_7);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(31, 10, 91, 31));
        label_8->setFont(font);
        Line6 = new QLineEdit(frame_7);
        Line6->setObjectName(QString::fromUtf8("Line6"));
        Line6->setGeometry(QRect(121, 10, 51, 31));
        Line6->setFont(font1);
        ButtonAngle6Up = new QPushButton(frame_7);
        ButtonAngle6Up->setObjectName(QString::fromUtf8("ButtonAngle6Up"));
        ButtonAngle6Up->setGeometry(QRect(180, 10, 31, 21));
        ButtonAngle6Down = new QPushButton(frame_7);
        ButtonAngle6Down->setObjectName(QString::fromUtf8("ButtonAngle6Down"));
        ButtonAngle6Down->setGeometry(QRect(180, 40, 31, 21));
        frame_8 = new QFrame(centralWidget);
        frame_8->setObjectName(QString::fromUtf8("frame_8"));
        frame_8->setGeometry(QRect(610, 680, 251, 101));
        frame_8->setFrameShape(QFrame::Box);
        frame_8->setFrameShadow(QFrame::Sunken);
        frame_8->setLineWidth(4);
        setAngleSilder8 = new QSlider(frame_8);
        setAngleSilder8->setObjectName(QString::fromUtf8("setAngleSilder8"));
        setAngleSilder8->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder8->setMinimum(-90);
        setAngleSilder8->setMaximum(90);
        setAngleSilder8->setPageStep(1);
        setAngleSilder8->setOrientation(Qt::Horizontal);
        label_9 = new QLabel(frame_8);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(31, 10, 91, 31));
        label_9->setFont(font);
        Line8 = new QLineEdit(frame_8);
        Line8->setObjectName(QString::fromUtf8("Line8"));
        Line8->setGeometry(QRect(121, 10, 51, 31));
        Line8->setFont(font1);
        ButtonAngle8Down = new QPushButton(frame_8);
        ButtonAngle8Down->setObjectName(QString::fromUtf8("ButtonAngle8Down"));
        ButtonAngle8Down->setGeometry(QRect(190, 40, 31, 21));
        ButtonAngle8Up = new QPushButton(frame_8);
        ButtonAngle8Up->setObjectName(QString::fromUtf8("ButtonAngle8Up"));
        ButtonAngle8Up->setGeometry(QRect(190, 10, 31, 21));
        frame_9 = new QFrame(centralWidget);
        frame_9->setObjectName(QString::fromUtf8("frame_9"));
        frame_9->setGeometry(QRect(590, 790, 301, 101));
        frame_9->setFrameShape(QFrame::Box);
        frame_9->setFrameShadow(QFrame::Sunken);
        frame_9->setLineWidth(4);
        setAngleSilder9 = new QSlider(frame_9);
        setAngleSilder9->setObjectName(QString::fromUtf8("setAngleSilder9"));
        setAngleSilder9->setGeometry(QRect(60, 60, 141, 20));
        setAngleSilder9->setMinimum(-90);
        setAngleSilder9->setMaximum(90);
        setAngleSilder9->setPageStep(1);
        setAngleSilder9->setOrientation(Qt::Horizontal);
        label_10 = new QLabel(frame_9);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(61, 30, 91, 31));
        label_10->setFont(font);
        Line9 = new QLineEdit(frame_9);
        Line9->setObjectName(QString::fromUtf8("Line9"));
        Line9->setGeometry(QRect(151, 30, 51, 31));
        Line9->setFont(font1);
        ButtonAngle9Down = new QPushButton(frame_9);
        ButtonAngle9Down->setObjectName(QString::fromUtf8("ButtonAngle9Down"));
        ButtonAngle9Down->setGeometry(QRect(210, 50, 31, 21));
        ButtonAngle9Up = new QPushButton(frame_9);
        ButtonAngle9Up->setObjectName(QString::fromUtf8("ButtonAngle9Up"));
        ButtonAngle9Up->setGeometry(QRect(210, 20, 31, 21));
        frame_10 = new QFrame(centralWidget);
        frame_10->setObjectName(QString::fromUtf8("frame_10"));
        frame_10->setGeometry(QRect(620, 580, 221, 81));
        frame_10->setFrameShape(QFrame::Box);
        frame_10->setFrameShadow(QFrame::Sunken);
        frame_10->setLineWidth(4);
        setAngleSilder7 = new QSlider(frame_10);
        setAngleSilder7->setObjectName(QString::fromUtf8("setAngleSilder7"));
        setAngleSilder7->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder7->setMinimum(-100);
        setAngleSilder7->setMaximum(100);
        setAngleSilder7->setPageStep(1);
        setAngleSilder7->setOrientation(Qt::Horizontal);
        label_11 = new QLabel(frame_10);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(31, 10, 91, 31));
        label_11->setFont(font);
        Line7 = new QLineEdit(frame_10);
        Line7->setObjectName(QString::fromUtf8("Line7"));
        Line7->setGeometry(QRect(121, 10, 51, 31));
        Line7->setFont(font1);
        ButtonAngle7Down = new QPushButton(frame_10);
        ButtonAngle7Down->setObjectName(QString::fromUtf8("ButtonAngle7Down"));
        ButtonAngle7Down->setGeometry(QRect(180, 40, 31, 21));
        ButtonAngle7Up = new QPushButton(frame_10);
        ButtonAngle7Up->setObjectName(QString::fromUtf8("ButtonAngle7Up"));
        ButtonAngle7Up->setGeometry(QRect(180, 10, 31, 21));
        line_time = new QLineEdit(centralWidget);
        line_time->setObjectName(QString::fromUtf8("line_time"));
        line_time->setGeometry(QRect(530, 270, 41, 31));
        line_time->setFont(font1);
        send = new QPushButton(centralWidget);
        send->setObjectName(QString::fromUtf8("send"));
        send->setGeometry(QRect(580, 270, 61, 31));
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(470, 270, 61, 31));
        label_6->setFont(font);
        frame_11 = new QFrame(centralWidget);
        frame_11->setObjectName(QString::fromUtf8("frame_11"));
        frame_11->setGeometry(QRect(1100, 460, 321, 151));
        frame_11->setFrameShape(QFrame::Box);
        frame_11->setFrameShadow(QFrame::Sunken);
        frame_11->setLineWidth(4);
        ButtonRunAll = new QPushButton(frame_11);
        ButtonRunAll->setObjectName(QString::fromUtf8("ButtonRunAll"));
        ButtonRunAll->setGeometry(QRect(10, 100, 81, 31));
        feedback = new QPushButton(frame_11);
        feedback->setObjectName(QString::fromUtf8("feedback"));
        feedback->setGeometry(QRect(230, 60, 81, 31));
        ButtonChooseFile = new QPushButton(frame_11);
        ButtonChooseFile->setObjectName(QString::fromUtf8("ButtonChooseFile"));
        ButtonChooseFile->setGeometry(QRect(10, 20, 81, 28));
        insert = new QPushButton(frame_11);
        insert->setObjectName(QString::fromUtf8("insert"));
        insert->setGeometry(QRect(10, 60, 81, 31));
        SaveFile = new QPushButton(frame_11);
        SaveFile->setObjectName(QString::fromUtf8("SaveFile"));
        SaveFile->setGeometry(QRect(120, 20, 81, 28));
        CleanTable = new QPushButton(frame_11);
        CleanTable->setObjectName(QString::fromUtf8("CleanTable"));
        CleanTable->setGeometry(QRect(230, 20, 81, 28));
        dele = new QPushButton(frame_11);
        dele->setObjectName(QString::fromUtf8("dele"));
        dele->setGeometry(QRect(120, 60, 81, 31));
        ButtonCountZero = new QPushButton(frame_11);
        ButtonCountZero->setObjectName(QString::fromUtf8("ButtonCountZero"));
        ButtonCountZero->setGeometry(QRect(120, 100, 81, 31));
        frame_12 = new QFrame(centralWidget);
        frame_12->setObjectName(QString::fromUtf8("frame_12"));
        frame_12->setGeometry(QRect(440, 20, 221, 81));
        frame_12->setFrameShape(QFrame::Box);
        frame_12->setFrameShadow(QFrame::Sunken);
        frame_12->setLineWidth(4);
        setAngleSilder10 = new QSlider(frame_12);
        setAngleSilder10->setObjectName(QString::fromUtf8("setAngleSilder10"));
        setAngleSilder10->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder10->setMinimum(-90);
        setAngleSilder10->setMaximum(90);
        setAngleSilder10->setPageStep(1);
        setAngleSilder10->setOrientation(Qt::Horizontal);
        label_13 = new QLabel(frame_12);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 10, 101, 31));
        label_13->setFont(font);
        Line10 = new QLineEdit(frame_12);
        Line10->setObjectName(QString::fromUtf8("Line10"));
        Line10->setGeometry(QRect(121, 10, 51, 31));
        Line10->setFont(font1);
        ButtonAngle10Down = new QPushButton(frame_12);
        ButtonAngle10Down->setObjectName(QString::fromUtf8("ButtonAngle10Down"));
        ButtonAngle10Down->setGeometry(QRect(180, 40, 31, 21));
        ButtonAngle10Up = new QPushButton(frame_12);
        ButtonAngle10Up->setObjectName(QString::fromUtf8("ButtonAngle10Up"));
        ButtonAngle10Up->setGeometry(QRect(180, 10, 31, 21));
        frame_13 = new QFrame(centralWidget);
        frame_13->setObjectName(QString::fromUtf8("frame_13"));
        frame_13->setGeometry(QRect(580, 120, 221, 81));
        frame_13->setFrameShape(QFrame::Box);
        frame_13->setFrameShadow(QFrame::Sunken);
        frame_13->setLineWidth(4);
        setAngleSilder11 = new QSlider(frame_13);
        setAngleSilder11->setObjectName(QString::fromUtf8("setAngleSilder11"));
        setAngleSilder11->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder11->setMinimum(-90);
        setAngleSilder11->setMaximum(90);
        setAngleSilder11->setPageStep(1);
        setAngleSilder11->setOrientation(Qt::Horizontal);
        label_14 = new QLabel(frame_13);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 10, 101, 31));
        label_14->setFont(font);
        Line11 = new QLineEdit(frame_13);
        Line11->setObjectName(QString::fromUtf8("Line11"));
        Line11->setGeometry(QRect(121, 10, 51, 31));
        Line11->setFont(font1);
        ButtonAngle11Down = new QPushButton(frame_13);
        ButtonAngle11Down->setObjectName(QString::fromUtf8("ButtonAngle11Down"));
        ButtonAngle11Down->setGeometry(QRect(180, 40, 31, 21));
        ButtonAngle11Up = new QPushButton(frame_13);
        ButtonAngle11Up->setObjectName(QString::fromUtf8("ButtonAngle11Up"));
        ButtonAngle11Up->setGeometry(QRect(180, 10, 31, 21));
        frame_14 = new QFrame(centralWidget);
        frame_14->setObjectName(QString::fromUtf8("frame_14"));
        frame_14->setGeometry(QRect(860, 120, 221, 81));
        frame_14->setFrameShape(QFrame::Box);
        frame_14->setFrameShadow(QFrame::Sunken);
        frame_14->setLineWidth(4);
        setAngleSilder12 = new QSlider(frame_14);
        setAngleSilder12->setObjectName(QString::fromUtf8("setAngleSilder12"));
        setAngleSilder12->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder12->setMinimum(-90);
        setAngleSilder12->setMaximum(90);
        setAngleSilder12->setPageStep(1);
        setAngleSilder12->setOrientation(Qt::Horizontal);
        label_15 = new QLabel(frame_14);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(10, 10, 101, 31));
        label_15->setFont(font);
        Line12 = new QLineEdit(frame_14);
        Line12->setObjectName(QString::fromUtf8("Line12"));
        Line12->setGeometry(QRect(121, 10, 51, 31));
        Line12->setFont(font1);
        ButtonAngle12Down = new QPushButton(frame_14);
        ButtonAngle12Down->setObjectName(QString::fromUtf8("ButtonAngle12Down"));
        ButtonAngle12Down->setGeometry(QRect(180, 40, 31, 21));
        ButtonAngle12Up = new QPushButton(frame_14);
        ButtonAngle12Up->setObjectName(QString::fromUtf8("ButtonAngle12Up"));
        ButtonAngle12Up->setGeometry(QRect(180, 10, 31, 21));
        frame_15 = new QFrame(centralWidget);
        frame_15->setObjectName(QString::fromUtf8("frame_15"));
        frame_15->setGeometry(QRect(860, 230, 221, 81));
        frame_15->setFrameShape(QFrame::Box);
        frame_15->setFrameShadow(QFrame::Sunken);
        frame_15->setLineWidth(4);
        setAngleSilder13 = new QSlider(frame_15);
        setAngleSilder13->setObjectName(QString::fromUtf8("setAngleSilder13"));
        setAngleSilder13->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder13->setMinimum(-90);
        setAngleSilder13->setMaximum(90);
        setAngleSilder13->setPageStep(1);
        setAngleSilder13->setOrientation(Qt::Horizontal);
        label_16 = new QLabel(frame_15);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(10, 10, 101, 31));
        label_16->setFont(font);
        Line13 = new QLineEdit(frame_15);
        Line13->setObjectName(QString::fromUtf8("Line13"));
        Line13->setGeometry(QRect(121, 10, 51, 31));
        Line13->setFont(font1);
        ButtonAngle13Down = new QPushButton(frame_15);
        ButtonAngle13Down->setObjectName(QString::fromUtf8("ButtonAngle13Down"));
        ButtonAngle13Down->setGeometry(QRect(180, 40, 31, 21));
        ButtonAngle13Up = new QPushButton(frame_15);
        ButtonAngle13Up->setObjectName(QString::fromUtf8("ButtonAngle13Up"));
        ButtonAngle13Up->setGeometry(QRect(180, 10, 31, 21));
        frame_16 = new QFrame(centralWidget);
        frame_16->setObjectName(QString::fromUtf8("frame_16"));
        frame_16->setGeometry(QRect(330, 120, 221, 81));
        frame_16->setFrameShape(QFrame::Box);
        frame_16->setFrameShadow(QFrame::Sunken);
        frame_16->setLineWidth(4);
        setAngleSilder14 = new QSlider(frame_16);
        setAngleSilder14->setObjectName(QString::fromUtf8("setAngleSilder14"));
        setAngleSilder14->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder14->setMinimum(-90);
        setAngleSilder14->setMaximum(90);
        setAngleSilder14->setPageStep(1);
        setAngleSilder14->setOrientation(Qt::Horizontal);
        label_17 = new QLabel(frame_16);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(10, 10, 101, 31));
        label_17->setFont(font);
        Line14 = new QLineEdit(frame_16);
        Line14->setObjectName(QString::fromUtf8("Line14"));
        Line14->setGeometry(QRect(121, 10, 51, 31));
        Line14->setFont(font1);
        ButtonAngle14Down = new QPushButton(frame_16);
        ButtonAngle14Down->setObjectName(QString::fromUtf8("ButtonAngle14Down"));
        ButtonAngle14Down->setGeometry(QRect(180, 40, 31, 21));
        ButtonAngle14Up = new QPushButton(frame_16);
        ButtonAngle14Up->setObjectName(QString::fromUtf8("ButtonAngle14Up"));
        ButtonAngle14Up->setGeometry(QRect(180, 10, 31, 21));
        frame_17 = new QFrame(centralWidget);
        frame_17->setObjectName(QString::fromUtf8("frame_17"));
        frame_17->setGeometry(QRect(50, 120, 221, 81));
        frame_17->setFrameShape(QFrame::Box);
        frame_17->setFrameShadow(QFrame::Sunken);
        frame_17->setLineWidth(4);
        setAngleSilder15 = new QSlider(frame_17);
        setAngleSilder15->setObjectName(QString::fromUtf8("setAngleSilder15"));
        setAngleSilder15->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder15->setMinimum(-90);
        setAngleSilder15->setMaximum(90);
        setAngleSilder15->setPageStep(1);
        setAngleSilder15->setOrientation(Qt::Horizontal);
        label_19 = new QLabel(frame_17);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(10, 10, 101, 31));
        label_19->setFont(font);
        Line15 = new QLineEdit(frame_17);
        Line15->setObjectName(QString::fromUtf8("Line15"));
        Line15->setGeometry(QRect(121, 10, 51, 31));
        Line15->setFont(font1);
        ButtonAngle15Down = new QPushButton(frame_17);
        ButtonAngle15Down->setObjectName(QString::fromUtf8("ButtonAngle15Down"));
        ButtonAngle15Down->setGeometry(QRect(180, 40, 31, 21));
        ButtonAngle15Up = new QPushButton(frame_17);
        ButtonAngle15Up->setObjectName(QString::fromUtf8("ButtonAngle15Up"));
        ButtonAngle15Up->setGeometry(QRect(180, 10, 31, 21));
        frame_18 = new QFrame(centralWidget);
        frame_18->setObjectName(QString::fromUtf8("frame_18"));
        frame_18->setGeometry(QRect(50, 220, 221, 81));
        frame_18->setFrameShape(QFrame::Box);
        frame_18->setFrameShadow(QFrame::Sunken);
        frame_18->setLineWidth(4);
        setAngleSilder16 = new QSlider(frame_18);
        setAngleSilder16->setObjectName(QString::fromUtf8("setAngleSilder16"));
        setAngleSilder16->setGeometry(QRect(30, 40, 141, 20));
        setAngleSilder16->setMinimum(-90);
        setAngleSilder16->setMaximum(90);
        setAngleSilder16->setPageStep(1);
        setAngleSilder16->setOrientation(Qt::Horizontal);
        label_20 = new QLabel(frame_18);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(10, 10, 101, 31));
        label_20->setFont(font);
        Line16 = new QLineEdit(frame_18);
        Line16->setObjectName(QString::fromUtf8("Line16"));
        Line16->setGeometry(QRect(121, 10, 51, 31));
        Line16->setFont(font1);
        ButtonAngle16Down = new QPushButton(frame_18);
        ButtonAngle16Down->setObjectName(QString::fromUtf8("ButtonAngle16Down"));
        ButtonAngle16Down->setGeometry(QRect(180, 40, 31, 21));
        ButtonAngle16Up = new QPushButton(frame_18);
        ButtonAngle16Up->setObjectName(QString::fromUtf8("ButtonAngle16Up"));
        ButtonAngle16Up->setGeometry(QRect(180, 10, 31, 21));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1790, 22));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "Motor0", 0, QApplication::UnicodeUTF8));
        Line0->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle0Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        ButtonAngle0Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindow", "Motor1", 0, QApplication::UnicodeUTF8));
        Line1->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle1Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        ButtonAngle1Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("MainWindow", "Motor2", 0, QApplication::UnicodeUTF8));
        Line2->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle2Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        ButtonAngle2Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("MainWindow", "Motor3", 0, QApplication::UnicodeUTF8));
        Line3->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle3Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        ButtonAngle3Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("MainWindow", "Motor4", 0, QApplication::UnicodeUTF8));
        Line4->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle4Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        ButtonAngle4Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("MainWindow", "Motor5", 0, QApplication::UnicodeUTF8));
        Line5->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle5Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        ButtonAngle5Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("MainWindow", "Motor6", 0, QApplication::UnicodeUTF8));
        Line6->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle6Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        ButtonAngle6Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("MainWindow", "Motor8", 0, QApplication::UnicodeUTF8));
        Line8->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle8Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        ButtonAngle8Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("MainWindow", "Motor9", 0, QApplication::UnicodeUTF8));
        Line9->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle9Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        ButtonAngle9Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("MainWindow", "Motor7", 0, QApplication::UnicodeUTF8));
        Line7->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle7Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        ButtonAngle7Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        line_time->setText(QApplication::translate("MainWindow", "1", 0, QApplication::UnicodeUTF8));
        send->setText(QApplication::translate("MainWindow", "\345\217\221\351\200\201", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("MainWindow", "Time", 0, QApplication::UnicodeUTF8));
        ButtonRunAll->setText(QApplication::translate("MainWindow", "|>", 0, QApplication::UnicodeUTF8));
        feedback->setText(QApplication::translate("MainWindow", "\346\211\223\345\274\200\345\217\215\351\246\210", 0, QApplication::UnicodeUTF8));
        ButtonChooseFile->setText(QApplication::translate("MainWindow", "\351\200\211\346\213\251\346\226\207\344\273\266", 0, QApplication::UnicodeUTF8));
        insert->setText(QApplication::translate("MainWindow", "\346\217\222\345\205\245\346\225\260\346\215\256", 0, QApplication::UnicodeUTF8));
        SaveFile->setText(QApplication::translate("MainWindow", "\344\277\235\345\255\230\346\226\207\344\273\266", 0, QApplication::UnicodeUTF8));
        CleanTable->setText(QApplication::translate("MainWindow", "\346\270\205\347\251\272\350\241\250\346\240\274", 0, QApplication::UnicodeUTF8));
        dele->setText(QApplication::translate("MainWindow", "\345\210\240\351\231\244\350\277\231\350\241\214", 0, QApplication::UnicodeUTF8));
        ButtonCountZero->setText(QApplication::translate("MainWindow", "\342\227\217", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("MainWindow", "Motor10", 0, QApplication::UnicodeUTF8));
        Line10->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle10Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        ButtonAngle10Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("MainWindow", "Motor11", 0, QApplication::UnicodeUTF8));
        Line11->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle11Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        ButtonAngle11Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("MainWindow", "Motor12", 0, QApplication::UnicodeUTF8));
        Line12->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle12Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        ButtonAngle12Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("MainWindow", "Motor13", 0, QApplication::UnicodeUTF8));
        Line13->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle13Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        ButtonAngle13Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("MainWindow", "Motor14", 0, QApplication::UnicodeUTF8));
        Line14->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle14Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        ButtonAngle14Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("MainWindow", "Motor15", 0, QApplication::UnicodeUTF8));
        Line15->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle15Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        ButtonAngle15Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("MainWindow", "Motor16", 0, QApplication::UnicodeUTF8));
        Line16->setText(QApplication::translate("MainWindow", "0", 0, QApplication::UnicodeUTF8));
        ButtonAngle16Down->setText(QApplication::translate("MainWindow", "-", 0, QApplication::UnicodeUTF8));
        ButtonAngle16Up->setText(QApplication::translate("MainWindow", "+", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
